---
kind: pipeline
type: docker
name: mail2clients

steps:
- name: build application
  image: maven:3.6.3-jdk-11-openj9
  commands:
  - cd mail2clients
  - mvn compile
  - mvn package

- name: Unit test
  image: maven:3.6.3-jdk-11-openj9
  commands:
  - cd mail2clients
  - mvn test

- name: build docker web image
  image: plugins/docker
  settings:
    dockerfile: Dockerfile_web
    context: .
    repo: mcarras1/mail2clients
    username: 
        from_secret: DOCKER_USERNAME
    password:
        from_secret: DOCKER_PASSWORD
    tag:
        - 1.0
        - latest

- name: build docker database image
  image: plugins/docker
  settings:
    dockerfile: Dockerfile_database
    context: .
    repo: mcarras1/mail2clientsdb
    username: 
        from_secret: DOCKER_USERNAME
    password:
        from_secret: DOCKER_PASSWORD
    tag:
        - 1.0
        - latest
