---
kind: pipeline
type: docker
name: mail2clients

steps:
- name: build and test
  image: maven:3.6.3-jdk-11-openj9
  commands:
  - cd mail2clients
  - mvn compile
  - mvn test
  - mvn package

- name: build docker web image
  image: plugins/docker
  repo: mcarras1/rampup2020
  settings:
    dockerfile: Dockerfile_web
    username: 
        from_secret: DOCKER_USERNAME
    password:
        from_secret: DOCKER_PASSWORD
    auto_tag: true

- name: build docker database image
  image: plugins/docker
  repo: mcarras1/rampup2020
  settings:
    dockerfile: Dockerfile_database
    username: 
        from_secret: DOCKER_USERNAME
    password:
        from_secret: DOCKER_PASSWORD
    auto_tag: true
