---
kind: pipeline
type: docker
name: mail2clients

steps:
- name: build and test
  image: maven:3.6.3-jdk-11-openj9
  pom: mail2clients/pom.xml
  commands:
  - mvn compile
  - mvn test
  - mvn package

- name: build docker web image
  image: plugins/docker
  repo: mcarras1/rampup2020
  dockerfile: Dockerfile.web
  settings:
    username: 
        from_secret: DOCKER_USERNAME
    password:
        from_secret: DOCKER_PASSWORD
  auto_tag: true

- name: build docker database image
  image: plugins/docker
  repo: mcarras1/rampup2020
  dockerfile: Dockerfile.database
  settings:
    username: 
        from_secret: DOCKER_USERNAME
    password:
        from_secret: DOCKER_PASSWORD
  auto_tag: true
