version: "3"
services:
    web:
        container_name: web
        build:
            context: .
            dockerfile: Dockerfile.web
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports: 
            - 8080:8080
        depends_on: 
            - database
            - smtp
    database:
        container_name: postgres
        build:
            context: .
            dockerfile: Dockerfile.database
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    smtp:
        container_name: smtp_mail2clients
        image: namshi/smtp
        restart: always
        environment: 
            GMAIL_USER: ${GMAIL_USER}
            GMAIL_PASSWORD: ${GMAIL_PASSWORD}
